name: "Terraform Test"

on:
  workflow_dispatch:
    inputs:
      folderId:
        description: "Folder Id"
        required: true

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var="folder_id=${{ github.event.inputs.folderId }}"
